services:
  - type: web
    name: ml-bootcamp
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: voila --port $PORT --no-browser --ResourceUseDisplay=True notebooks/
